// authentication
export const REGISTER ="REGISTER";
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN ="LOGIN";
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT ="LOGOUT"

export const SET_ALERT ="SET_ALERT"
export const REMOVE_ALERT ="REMOVE_ALERT"

export const GET_CATEGORY = "GET_CATEGORY"
export const GET_SINGLE_CATEGORY = "GET_SINGLE_CATEGORY"
export const POST_CATEGORY = "POST_CATEGORY"
export const UPDATE_CATEGORY= "UPDATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"

export const GET_ALL_PRODUCT ="GET_ALL_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"
export const POST_PRODUCT = "POST_PRODUCT"
export const UPDATE_PRODUCT= "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
